### ISSUE TITLE
Gaomon S620 detected as unknown huion tablet

### ISSUE THREAD

**Issue by cillynder** [InfinityGhost/TabletDriver#18]
Tried to follow the FAQ for input not being detected, still won't work

## Hardware/software information
Windows Version: Windows 10 Pro

Tablet Driver version: 0.3.0

Tablet model: 

## Logs
[startuplog.txt](https://github.com/InfinityGhost/TabletDriver/files/3750141/startuplog.txt)

**Comment by RuFous56** [comment]
delete the huion.cfg in the config file
https://i.gyazo.com/1f2148de36f8ae7f1dbc10c881eb5af1.png
https://i.gyazo.com/2c684e549b77d0828a18cc6312eab74c.png

**Comment by Nykreuz** [comment]
Hi!, i got this tablet yesterday and got the same issue. Still not working after deleting huion.cfg....

**Comment by Jezpu** [comment]
I have the same problem :(

**Comment by RuFous56** [comment]
this is what im using
https://drive.google.com/open?id=1hYIsblKwy9tf3OFA7s0NchS27Ssw5I-N

**Comment by RuFous56** [comment]
another thing that might help is install the official gaomon drivers.
Open the gaomon drivers
Click Apply
Click Ok
Then follow these images
https://imgur.com/a/UmvBfC0
the gaomon symbol could be orange for you (that doesnt mean anything)

**Comment by Nykreuz** [comment]
> 
> 
> this is what im using
> https://drive.google.com/open?id=1hYIsblKwy9tf3OFA7s0NchS27Ssw5I-N

can´t open it and i already tried installing gaomon drivers

**Comment by cillynder** [comment]
Ok I've got it working
For those who have the same issue, here's what I did:
- Copy the S620 config from `gaomon.cfg`
- Replace the `Huion HS64 (HIDTablet)` section in `huion.cfg` with the S620 config
- Install the official Gaomon drivers
- Install VMulti
- Uninstall Gaomon drivers

You can also replace huion.cfg with [this](https://cdn.discordapp.com/attachments/410954867067322370/637915565297762315/huion.cfg) if you want to skip the first two steps

**Comment by Nykreuz** [comment]
oh my god. thank you so much!!! Finally osu is playable without smoothness taking all my aim out from jumps xDDDD

**Comment by TTi1** [comment]
It worked for me too thank you
they should include those instructions in their readme

**Comment by InfinityGhost** [comment]
I need to make this not an issue at all for the S620. I'm going to work on a fix that will solve this HS64 replacement trick so its not necessary.

**Comment by InfinityGhost** [comment]
Fixed in #24
