### ISSUE TITLE
Changing tablet area has no effect.

### ISSUE THREAD

**Issue by Lykrin** [InfinityGhost/TabletDriver#23]
I have recently performed clean windows install before setting up all the programs and drivers. After installing the TabletDriver and all the required files I tried to change tablet area. Which is when I discovered that saving the settings doesn't change the area in the tablet.  

Any help would be greatly appreciated. So far I have tried:
-Removing tablet drivers from "Device manager" 
-Reinstalling Vmulti drivers
-Removing the tablet from windows devices

Every time I remove the tablet it seems like windows simply re-installs some driver. 

## Hardware/software information
Windows Version: 1903

Tablet Driver version: 0.3.0

Tablet model: XP-PEN 640

## Logs
[startuplog.txt](https://github.com/InfinityGhost/TabletDriver/files/3806190/startuplog.txt)

**Comment by InfinityGhost** [comment]
I'm assuming you're up to date on all windows updates? This has been a recurring issue with windows update from what I can tell.

**Comment by Lykrin** [comment]
Yes. I have updated all that stuff right after installing basic drivers (GPU etc.) Do you know of some way to remedy this problem? Perhaps total removal of windows automatic driver installing. I really wouldn't like to go back to earlier versions of windows.

**Comment by InfinityGhost** [comment]
User BestWingMan on my discord has the exact same issue from what I can tell, and it seems to do with windows automatically installing drivers. I'm going to give it some work before I release v0.3.1

**Comment by Lykrin** [comment]
Thanks a lot for that :) Also, would you mind sharing the discord server for the driver? If there is one of course.

**Comment by InfinityGhost** [comment]
https://discord.gg/P3GYdUS

**Comment by InfinityGhost** [comment]
Confirmed fixed, turned out to be antivirus.
> [Lykrin | 11/16/19 at 3:44 PM EST](https://discordapp.com/channels/615607687467761684/617030189494566913/645363564281987123)
> It seems to have been windows defender/other antivirus all along. After allowing the files/disabling the antivirus it all works flawlessly.
