### ISSUE TITLE
Faulty config file for Gaomon S620

### ISSUE THREAD

**Issue by Fellonimo** [InfinityGhost/TabletDriver#30]
Windows Version:  Windows 10 Home 64-bit

Tablet Driver version:  0.3.1

Tablet model: Gaomon S620

I tried connecting my Gaomon S620 but it wasn't recognized. 
I fixed it by changing:

"CheckString 201 "OEM02_T18e_190329""

To:

"CheckString 201 "OEM02_T18e_190814""

In the "\config\gaomon.cfg" 

My tablet has since worked perfectly for the last 2 days.

**Comment by InfinityGhost** [comment]
This is a known issue, i'm working on a fix for this that I probably should have released with v0.3.1

**Comment by Fellonimo** [comment]
OK, good. I looked thorugh the issues and didn't find this one, I've must have missed it:/
