### ISSUE TITLE
Gaomon S620 detected as Unknown Huion Tablet

### ISSUE THREAD

**Issue by loopinger** [InfinityGhost/TabletDriver#32]
I need help pls help:)
![image](https://user-images.githubusercontent.com/57836787/69360572-7c199a80-0c93-11ea-90e1-9ae59466ad22.png)

## Hardware/software information
Windows Version: 1909 windows 10 pro

Tablet Driver version: 0.3.0

Tablet model: gaomon s620

## Logs
`startuplog.txt`

**Comment by InfinityGhost** [comment]
### Try this newest release
https://github.com/InfinityGhost/TabletDriver/releases/tag/v0.3.1a

**Comment by loopinger** [comment]
ty

**Comment by InfinityGhost** [comment]
I'm assuming that the new release works. Closing this issue.
