### ISSUE TITLE
My XP Pen G430S won't get detected

### ISSUE THREAD

**Issue by rasikhq** [InfinityGhost/TabletDriver#33]
I believe I have the model B (the new one) as well since I ordered this like a week ago, I followed the installation steps, it said installed successfully.

When I run it the console at the end says tablet not found.

**Comment by xCuri0** [comment]
@DizzasTeR Your sure your using the latest version ? The latest version should include a config for it. If that doesn't work you may have a different model that isn't supported (for now).

Whats the model written on the bottom of the tablet ?

**Comment by rasikhq** [comment]
I have the 0.3.0 version, I guess that's the latest one. The config folder has xp-pen config file

![image](https://user-images.githubusercontent.com/16344370/69406924-10800d80-0d25-11ea-9719-0d006551629a.png)

and this is what the back of my tablet looks like:

![20191122_123724](https://user-images.githubusercontent.com/16344370/69406946-1e359300-0d25-11ea-852f-4311e94dd12f.jpg)

**Comment by xCuri0** [comment]
@DizzasTeR your version is old. try this one https://github.com/InfinityGhost/TabletDriver/releases/download/v0.3.1a/TabletDriver.v0.3.1a.zip

**Comment by rasikhq** [comment]
Ay, you're a life saver mate, I can't believe I was being a try-hard with an older version wondering what's wrong.

Thank you, it detected now! <3
