### ISSUE TITLE
Windows detects trojans

### ISSUE THREAD

**Issue by ariaeon** [InfinityGhost/TabletDriver#36]
Hey, 

Ever since 0.3.1 my windows quarantines the .exe immediately because it claims to find trojans. I know very little of this so I'm a bit paranoid but I don't think you're malicious so could this get solved? :> Attached is a screenshot of the errors/warnings i get

## Hardware/software information
Windows Version: 10

Tablet Driver version: 0.3.1 
![ApplicationFrameHost_2019-12-04_230441](https://user-images.githubusercontent.com/37826944/70185693-98352700-16ea-11ea-84e0-8db02f1b8599.png)

Tablet model: Guion s620 

## Logs
`startuplog.txt`

**Comment by InfinityGhost** [comment]
The releases are built on the GitHub servers, so its clean. This is a false positive.
