### ISSUE TITLE
no input with custom driver on Gaomon S620

### ISSUE THREAD

**Issue by urleman** [InfinityGhost/TabletDriver#40]
Not sure what I'm dong wrong.  
Unzipped the driverGUI folder straight to C://
Installed Vmulti and Gaomon driver 
Gaomon driver is not running parallel to this driver

TDGUI doesn't give me any errors but I'm still getting no input at all.
Its a new tablet and runs as intended when I just use the Gaomon driver.

## Hardware/software information
Windows Version: Win10 64 bit

Tablet Driver version: v0.3.1a

Tablet model: Gaomon S620

[startuplog.txt](https://github.com/InfinityGhost/TabletDriver/files/4007623/startuplog.txt)

**Comment by jjhhgg100123** [comment]
Did you make an anti virus exception? Could be why.

**Comment by urleman** [comment]
I added an exception for the driver folder but that didn't change anything.

**Comment by urleman** [comment]
After looking through the closed issues I managed to solve the problem by reinstalling huion and vmulti drivers via the bat files from the old driver release. Pretty sure I tried these steps before but this time it worked.
