### ISSUE TITLE
[Resolved]XP-Pen Deco 01 V2 not detected

### ISSUE THREAD

**Issue by Kashouryo** [InfinityGhost/TabletDriver#41]
Looks like XP-PEN changed the tablet firmware one more time...
At first, TabletDriver can not even detect my Deco 01 V2 because the HIDTablet was incorrect based on this issue: https://github.com/hawku/TabletDriver/issues/465
After I changed the HIDTablet from 0x28BD 0x0902 0xFF0A 0x0001 to 0x28BD 0x0905 0xFF0A 0x0001, TabletDriver can reconise it but still can't use it. Looks like the InitReport also needs to change.

As far as I know, only XP-Pen likes to have multiple tablets under the same module number.

![image](https://user-images.githubusercontent.com/37679684/72641938-47475e00-3939-11ea-9e06-1bb0e3ef2884.png)

## Hardware/software information
Windows Version: Windows 10 1903

Tablet Driver version: 0.3.1a

Tablet model: XP-Pen Deco 01 v2

## Logs
`startuplog.txt`
[https://pastebin.com/MbZBGsPv](https://pastebin.com/MbZBGsPv)
[https://pastebin.com/q8pBjU3G](https://pastebin.com/q8pBjU3G)

**Comment by pomidorfarm** [comment]
reportlength 12
Initreport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x00

Quote from InfinityGhost'discord channel 
(https://discord.gg/P3GYdUS)

**Comment by Kashouryo** [comment]
Thanks! It worked like a charm!

**Comment by flleeppyy** [comment]
Im having the same issue with the same tablet. I'm clueless as to what I do.
The driver just doesn't work and says Tablet not Found, yet its in the supported tablets.

**Comment by flleeppyy** [comment]
and it seems to me that its ONLY scanning for wacom tablets.

**Comment by pomidorfarm** [comment]
Open xp-pen.cfg of TabletDriver\config
search deco 01 v2 and change like this

HIDTablet 0x28BD 0x0905 0xFF0A 0x0001
Name "XP-Pen Deco 01 v2"
ReportId 0x02
ReportLength 12
DetectMask 0x80
MaxX 25400
MaxY 15875
MaxPressure 8191
Width 254.0
Height 158.75
InitReport 0x02 0xB0 0x04 0x00 0x00 0x00 0x00 0x00 0x00 0x00
