### ISSUE TITLE
driver stopped

### ISSUE THREAD

**Issue by chuyin1289** [InfinityGhost/TabletDriver#44]
## Hardware/software information
Windows Version: 10 64bits

Tablet Driver version: v0.3.1a

Tablet model: Huoin HS64

## Logs

[startuplog.txt](https://github.com/InfinityGhost/TabletDriver/files/4272649/startuplog.txt)

**Comment by InfinityGhost** [comment]
Try installing the Huion driver and killing it in task manager once it starts

**Comment by chuyin1289** [comment]
it work, thanks

**Comment by ghost** [comment]
If the huion driver starts when your computer starts then go to the task manager then go to the startup tab and disable it from starting.

**Comment by chuyin1289** [comment]
thanks for the tip
