### ISSUE TITLE
[XP PEN DECO1] Crash on Start cannot use

### ISSUE THREAD

**Issue by MakcSan** [InfinityGhost/TabletDriver#45]
## Hardware/software information
Windows Version: 10

Tablet Driver version: Latest

Tablet model: XP pen deco1

## Logs
Theres no logs idk where it will saved but i cannot found it on TabletDriver Folder

**Comment by InfinityGhost** [comment]
Check to make sure that you followed the installation instructions correctly, you're likely missing the frameworks.

**Comment by MakcSan** [comment]
thanks problem was on my brain haha i was stupid
