### ISSUE TITLE
Windows 2004 detects the driver as an Virus

### ISSUE THREAD

**Issue by MaxKruse** [InfinityGhost/TabletDriver#53]
This driver is being detected as a virus in the newest windows update. 
Trojan:Win32/Persistence!rfn

Why is this? https://www.virustotal.com/gui/file/baa352adb725d6d984688f93498e04fa95d077e7f3c6911e4a71cf9f3bd50b79/detection

## Hardware/software information
Windows Version:  Version 2004 Build 19041.329

Tablet Driver version: 0.3.1a

Tablet model: CTL-470(k)

## Logs
[startuplog.txt](https://github.com/InfinityGhost/TabletDriver/files/4803527/startuplog.txt)

**Comment by InfinityGhost** [comment]
It's a known issue, its a false positive. Building the program from source code still has the exact same problem, which is why I ended up moving to my [OpenTabletDriver](https://github.com/InfinityGhost/OpenTabletDriver) project
