### ISSUE TITLE
Bitdefender, Chrome, and Firefox false positives

### ISSUE THREAD

**Issue by yellowsink** [InfinityGhost/TabletDriver#60]
## Hardware/software information
Windows Version: 10 x64

Tablet Driver version: v0.3.1a

Tablet model: CTL-460

Bitdefender, Google Chrome, and Firefox all mark the zip and exes as viruses.

EDIT: Real issue is apparently a need for a new release tag

**Comment by ghost** [comment]
#56 removes many of the false positives but a new release tag has not been made. If you compile TabletDriver you should be fine though.

**Comment by yellowsink** [comment]
Ah okay then. Thanks.
