### ISSUE TITLE
Installing VMulti driver fails: "devcon.exe failed."

### ISSUE THREAD

**Issue by Marfolino** [InfinityGhost/TabletDriver#8]
## Hardware/software information
Windows Version: Windows 10

Tablet Driver version: 

Tablet model: CTL-490

So after i uninstalled all the Wacom drivers, unplugged the Tablet and opened the install_vmulti_64 file this pops up:
![driverissue](https://user-images.githubusercontent.com/54444458/63599080-18fb6780-c5c1-11e9-9d05-b0133d8251a5.PNG)

I know that there are others having the same problem but looking around the issues i didn't find a solution. Hopefully someone can help me 

**edit
I did all of this with the hawku driver.. don't know if it changes something

**Comment by InfinityGhost** [comment]
1. Run `remove_vmulti_driver.bat`
2. Run `install_vmulti_driver.bat`

**Comment by Marfolino** [comment]
if i normally click on it this appears
![driverissue2](https://user-images.githubusercontent.com/54444458/63626847-289c9f80-c605-11e9-9176-2270458cf31a.PNG)
if I open it as an amministrator when i click enter the window instantly disappears
**edit
after a few minutes i got an amministrator permissions request and after allowing it I got this
![driverissue3](https://user-images.githubusercontent.com/54444458/63627102-533b2800-c606-11e9-971e-64075ab30490.PNG)

**Comment by InfinityGhost** [comment]
So now that you've got it to uninstall, try installing vmulti again.

**Comment by Marfolino** [comment]
just tried with the install_vmulti_driver.bat file but again, i get this after a few minutes
![driverissue4](https://user-images.githubusercontent.com/54444458/63627481-369fef80-c608-11e9-94ed-47020fae8f2f.PNG)

**Comment by InfinityGhost** [comment]
FIgured it out from my own testing, make sure that it's installing the right version. If you're running 64 bit windows, run the file `/driver_vmulti/install_vmulti_64.bat` and this will most likely install correctly.

**Comment by InfinityGhost** [comment]
Try the [newest release](https://github.com/InfinityGhost/TabletDriver/releases/tag/v0.3.0-pre), and use the included VMulti driver installer.

**Comment by InfinityGhost** [comment]
Inactive thread, closing issue.
